//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASGLOBAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Contract_ID { get; set; }
    
        public virtual Contracts Contracts { get; set; }
    }
}
